# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Artpass' do
    pod 'SwiftDate', '~> 2.0'
	pod 'ObjectMapper', '~> 1.0'
	pod 'Alamofire', '~> 3.0'
#  pod 'AlamofireObjectMapper', '~> 2.1'
end

